--[[
Patch for Boomsticks and Sharpsticks
Author: m-bo-one
--]]

_G.mbo_arena_items["bar_arena_fight_4"] = {
    "wpn_knife",
    "wpn_ak74m_n",
    "ammo_5.45x39_fmj",
    "ammo_5.45x39_fmj",
    "helm_respirator_old",
    "stalker_outfit",
    "bandage",
    "bandage",
}
_G.mbo_arena_items["bar_arena_fight_5"] = {
    "wpn_knife",
    "wpn_abakan_n",
    "ammo_5.45x39_ap",
    "ammo_5.45x39_ap",
    "helm_resp",
    "svoboda_light_outfit",
    "medkit",
    "bandage",
}
